---
title: Material Drifter
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  film:
    title: Film
    output: true
  mixed_media:
    title: Mixed Media
    output: true
  posts:
    title: Posts
    output: true
  prints:
    title: Prints
    output: true
  quilts:
    title: Quilts
    output: true
  uploads:
    title: Uploads
    output: true
  zines:
    title: Zines
    output: true
markdown: kramdown
permalink: pretty
tagline: A Jekyll theme
description: A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a>
  theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo"
  target="_blank">@mdo</a>.
url: 
baseurl: "/"
